FROM python:3.6

RUN pip install celery==4.2.0

ENV C_FORCE_ROOT=1

COPY ./app /app
WORKDIR /app

ENV PYTHONPATH=/app

# Start a celery worker with a single
CMD celery worker -A tasks -l info -Q main-queue -c 1
